services:
  db:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=boilerplate
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    depends_on:
      - db
    networks:
      - app_network
      
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - app_network

  django:
    build: .
    command: python boilerplate/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./boilerplate:/app/boilerplate
    ports:
      - "8000:8000"
    networks:
      - app_network

    develop:
      watch:
        - action: sync
          path: .
          target: /app

          ignore:
            - .venv/

        - action: rebuild
          path: ./pyproject.toml

    
volumes:
  postgres_data:

networks:
  app_network:  
