# Generated by Django 5.1.3 on 2024-12-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_exercise_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='uuid',
        ),
    ]
