name: Teste de Linter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test_code_linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sincronizar venv
        run: uv sync --dev

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SECRET_KEY: "SECRET_KEY"
          envkey_DEBUG: 1

      - name: Executar Linter
        run: uv run task lint
